## Author: Aakanksha Singh
## Date: 2 August 2022
## Version: 1.0
## Aim: Loading the libraries required for the project

library("TENxPBMCData")
library("SingleCellExperiment")
library("scater")
library("scran")
library("celldex")
library("SingleR")
library("tibble")
library("dplyr")
library("biomaRt")
library("tidyr")
library("tibble")
library("BiocSingular")
library("ensembldb")
library("ggplot2")
library("SPOTlight")
library("SpatialExperiment")
library("NMF")
library("SpatialDecon")
library("Seurat")
library("GeomxTools")
library("immunedeconv")
library("scRNAseq")
library(data.table)
library(stringr)
library(RColorBrewer)
library("ggpubr")
library(preprocessCore)
library(tidyverse)
library(matrixStats)
