---
title: "normalisation_comparison_in_deconvolution"
author: "Aakanksha Singh"
date: "2023-08-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r, message=FALSE}
source("library_loading.R")
source("processing_sce.R")
source("Generating_a_pseudobulk_sample.R")
source("updated_spatial_deconv.R")
source("bootstrapping_without_subsampling.R")
source("Spotlight_deconv.R")
source("spatial_deconv.R")
source("updated_spatial_deconv.R")
```

## For parallelising forloop for bootstrapping
```{r}
# parallel::detectCores()
# n.cores =4
# my.cluster <- parallel::makeCluster(
#   n.cores,
#   type = "FORK"
# )
# 
# doParallel::registerDoParallel(cl = my.cluster)
# foreach::getDoParRegistered()
# foreach::getDoParWorkers()

#stopCluster(cl=my.cluster)
```

# Testing signature matrices with pseudobulk samples
```{r}
pbmc6k <- readRDS("Raw_annotated_data/pbmc6k.rds")
cell_count_pbmc6k <- as.data.frame(table(pbmc6k$cell)) %>% 
                     dplyr::rename("cell_type"="Var1")

pbmc8k <- readRDS("Raw_annotated_data/pbmc8k.rds")
cell_count_pbmc8k <- as.data.frame(table(pbmc8k$cell)) %>% 
                     dplyr::rename("cell_type"="Var1")

liver <- readRDS("Raw_annotated_data/liver.rds")
cell_count_liver <- as.data.frame(table(liver$cell)) %>% 
                    dplyr::rename("cell_type"="Var1")

signature_reference <- readRDS("Data/signature_reference") 
```

# Benchmarking normalisation function
```{r}
benchmarking_normalisation <- function(n)
{
 # PBMC6k Dataset
pbmc6k_cell_table <-data.frame("cell_type"= c ("B cells","Monocytes","NK cells","T cells")) %>% 
                    left_join(cell_count_pbmc6k, by = c("cell_type" = "cell_type")) %>% rowwise() %>% 
                    mutate(inDeconv = as.integer(runif(1,min=10,max = Freq))) %>%  as.data.frame()

pbmc6k_cell_table <- pbmc6k_cell_table %>% mutate(inDeconv_Frac = inDeconv/sum(inDeconv))

pbmc6k_for_loop<- generating_raw_pseudobulk_matrix(pbmc6k,"pbmc6k",pbmc6k_cell_table[1,1],pbmc6k_cell_table[1,3],
                                      pbmc6k_cell_table[2,1],pbmc6k_cell_table[2,3],
                                      pbmc6k_cell_table[3,1],pbmc6k_cell_table[3,3],
                                      pbmc6k_cell_table[4,1],pbmc6k_cell_table[4,3])

## PBMC8K Dataset

pbmc8k_cell_table <-data.frame("cell_type"= c ("B cells","Monocytes","NK cells","T cells")) %>% 
                    left_join(cell_count_pbmc8k, by = c("cell_type" = "cell_type")) %>% rowwise() %>% 
                    mutate(inDeconv = as.integer(runif(1,min=10,max=Freq))) %>% as.data.frame()

pbmc8k_cell_table <- pbmc8k_cell_table %>% mutate(inDeconv_Frac = inDeconv/sum(inDeconv))

pbmc8k_for_loop<- generating_raw_pseudobulk_matrix(pbmc8k,"pbmc8k",pbmc8k_cell_table[1,1],pbmc8k_cell_table[1,3],
                                      pbmc8k_cell_table[2,1],pbmc8k_cell_table[2,3],
                                      pbmc8k_cell_table[3,1],pbmc8k_cell_table[3,3],
                                      pbmc8k_cell_table[4,1],pbmc8k_cell_table[4,3])

## Immune liver Dataset
liver_cell_table <-data.frame("cell_type"= c ("B cells","Monocytes","NK cells","T cells")) %>% 
                    left_join(cell_count_liver, by = c("cell_type" = "cell_type")) %>% rowwise() %>% 
                    mutate(inDeconv = as.integer(runif(1,min=10,max=Freq))) %>% as.data.frame()
liver_cell_table <- liver_cell_table %>% mutate(inDeconv_Frac = inDeconv/sum(inDeconv))

liver_for_loop<- generating_raw_pseudobulk_matrix(liver,"liver",liver_cell_table[1,1],liver_cell_table[1,3],
                                      liver_cell_table[2,1],liver_cell_table[2,3],
                                      liver_cell_table[3,1],liver_cell_table[3,3],
                                      liver_cell_table[4,1],liver_cell_table[4,3])

## Merging to make a pseudobulk dataset
deconv_table<- merge(liver_for_loop,pbmc8k_for_loop,by.x="HUGO",by.y="HUGO", all=TRUE) %>% merge(pbmc6k_for_loop,by="HUGO",all=TRUE)

deconv_table_matrix= deconv_table %>% column_to_rownames(var = "HUGO") %>% as.matrix()

# TPM normalised_values
tpm_deconv_table <- (deconv_table_matrix/colSums(deconv_table_matrix, na.rm = TRUE))*1000000
tpm_deconv_df <- as.data.frame(tpm_deconv_table) %>% rownames_to_column('HUGO')

# Q3 normalised ( normalised to the 75th percentile)
Q3_values = unlist(apply(deconv_table_matrix, 2,quantile, 0.75, na.rm = TRUE))
q3_deconv_table<- deconv_table_matrix / Q3_values
q3_deconv_df<- as.data.frame(q3_deconv_table) %>% rownames_to_column('HUGO')

# Quantile normalised
quantile_deconv_table <- normalize.quantiles(deconv_table_matrix,keep.names=TRUE)
quantile_deconv_df <- as.data.frame(quantile_deconv_table) %>% rownames_to_column('HUGO')

# Results for each normalisation type
result_raw <-bootstrapping_without_subsampling_updated_for_testing_normalisation(deconv_table,pbmc6k_cell_table,pbmc8k_cell_table,liver_cell_table)
result_tpm <-bootstrapping_without_subsampling_updated_for_testing_normalisation(tpm_deconv_df,pbmc6k_cell_table,pbmc8k_cell_table,liver_cell_table)
result_q3 <-bootstrapping_without_subsampling_updated_for_testing_normalisation(q3_deconv_df,pbmc6k_cell_table,pbmc8k_cell_table,liver_cell_table)
result_quantile <-bootstrapping_without_subsampling_updated_for_testing_normalisation(quantile_deconv_df,pbmc6k_cell_table,pbmc8k_cell_table,liver_cell_table)

# Adding the loop number to each run
result_raw$bootstrap_run=n
result_tpm$bootstrap_run=n
result_q3$bootstrap_run=n
result_quantile$bootstrap_run=n

res_list= list(result_raw= result_raw,
               result_tpm=result_tpm,
               result_q3=result_q3,
               result_quantile=result_quantile)
return(res_list)
}
```

# Bootstrapping
```{r}
res_list_all = list(result_raw=data.frame(),
                    result_tpm= data.frame(),
                    result_q3 = data.frame(),
                    result_quantile = data.frame())

start_time= Sys.time()
for (i in 1:30)
  { 
  tryCatch({res_list= benchmarking_normalisation(i)},error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
  res_list_all <- list(result_raw = rbind(res_list_all$result_raw, res_list$result_raw),
                       result_tpm = rbind(res_list_all$result_tpm, res_list$result_tpm),
                       result_q3 = rbind(res_list_all$result_q3, res_list$result_q3),
                       result_quantile = rbind(res_list_all$result_quaantile, res_list$result_quantile))
   print(paste0(i,"/30 of the Bootstrap done"))

}

end_time= Sys.time()
end_time - start_time
```


```{r}
original_data= res_list_all

res_list_all$result_raw
```

```{r}
tables_for_plotting <- function(cell_deconvolutions)

{
pb6k<- cell_deconvolutions %>% 
       dplyr::select(cell_type,pbmc6k,pbmc6k_actual,deconv_type) %>% 
       mutate("Dataset"="pbmc6k") %>% 
       dplyr::rename("Predicted_values"="pbmc6k","True_values"="pbmc6k_actual")

pb8k <- cell_deconvolutions %>% 
        dplyr::select(cell_type,pbmc8k,pbmc8k_actual,deconv_type) %>% 
        mutate("Dataset"="pbmc8k") %>% 
        dplyr::rename("Predicted_values"="pbmc8k","True_values"="pbmc8k_actual")

liv <- cell_deconvolutions %>% 
       dplyr::select(cell_type,liver,liver_actual,deconv_type) %>% 
       mutate("Dataset"="Liver") %>% 
       dplyr::rename("Predicted_values"="liver","True_values"="liver_actual")

cell_deconvolutions_for_plotting = rbind(pb6k,pb8k,liv) %>% 
       mutate(cell_type=ifelse(cell_type=="Macropahge","Macrophage",cell_type))

return(cell_deconvolutions_for_plotting)

}

normalisation_benchmarking <- lapply(res_list_all, tables_for_plotting)
save(normalisation_benchmarking,file = "Intermediate_data/normalisation_benchmarking.RData")
```


```{r}
load("Intermediate_data/normalisation_benchmarking.RData")
```

```{r}
raw_results= normalisation_benchmarking$result_raw
tpm_results=normalisation_benchmarking$result_tpm
q3_results=normalisation_benchmarking$result_q3
quantile_results=normalisation_benchmarking$result_quantile
```


```{r}
deconv_type_plots <- function(cell_deconvolutions_for_plotting,deconv_method, plot_title)
{
  nb.cols <- 18
  mycolors <- colorRampPalette(brewer.pal(11, "Set3"))(nb.cols)
  
  cell_deconvolutions_for_plotting %>% 
  dplyr::filter(deconv_type==deconv_method) %>% 
  ggplot(aes(x=(True_values),y=(Predicted_values), color,group=cell_type)) + geom_point(aes( color=cell_type), size=3) +
    scale_color_manual (values = c ( "B cell"  =  "#8DD3C7" , "Macrophage"  =  "#FFFFB3","Monocyte"  =  "#BEBADA", "Neutrophil"  =  "#FB8072", "NK cell"  =  "#80B1D3" , "T cell"  =  "#FDB462" ,"Myeloid dendritic cell"  =  "#B3DE69" ,      "uncharacterized cell"  =  "#FCCDE5",  "cytotoxicity score"  =  "#C9B4A7" , "Macrophage/Monocyte"  =  "#D9D9D9",       "Endothelial cell"  =  "#BC80BD" ,  "Cancer associated fibroblast"  =  "#CCEBC5" ,"Progenitor" = "#573F94","Dendritic cell" = "#B3DE69", "Mast cell"="#E6B9A1","Plasma cell"="#E6E6CA","Fibroblast cell"="#CCEBC5")) +
    geom_smooth(method = "lm", formula = y~x, col = "black") +
    scale_shape_manual(values=c(0,1,2,3, 16, 17,11,4,8))  + ggtitle(plot_title) + theme(plot.title = element_text(hjust = 0.5)) +   
    theme(axis.text.y   = element_text(size=14),
          axis.text.x   = element_text(size=14),
          axis.title.y  = element_text(size=14),
          axis.title.x  = element_text(size=14),
          panel.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.line = element_line(colour = "black"),
          panel.border = element_rect(colour = "black", fill=NA, size=1)) +                                                                                                                                      
    xlab("Actual proportions") +
    ylab("Predicted proportions")
}
```

```{r}

raw_graphs <- ggarrange(
  deconv_type_plots(raw_results,"Quantiseq", "Raw Quantiseq"),
  deconv_type_plots(raw_results,"EPIC", "Raw Epic"),
  deconv_type_plots(raw_results,"MCP", "Raw MCP"),
  deconv_type_plots(raw_results,"Spotlight", "Raw Spotlight"),
  deconv_type_plots(raw_results,"Spatial_deconv_cus", "Raw Spatial Decon ( custom signature 8k)"),
  deconv_type_plots(raw_results,"Spatial_deconv_tme", "Raw Spatial Decon (TME signature)"),
  widths=c(1,1,1,1,1,1), align="v", nrow =6, ncol=1,common.legend = TRUE, legend = "top")
  
  tpm_graphs <- ggarrange(
  deconv_type_plots(tpm_results,"Quantiseq", "TPM Quantiseq"),
  deconv_type_plots(tpm_results,"EPIC", "TPM Epic"),
  deconv_type_plots(tpm_results,"MCP", "TPM MCP"),
  deconv_type_plots(tpm_results,"Spotlight", "TPM Spotlight"),
  deconv_type_plots(tpm_results,"Spatial_deconv_cus", "TPM Spatial Decon ( custom signature 8k)"),
  deconv_type_plots(tpm_results,"Spatial_deconv_tme", "TPM Spatial Decon (TME signature)"),
  widths=c(1,1,1,1,1,1), align="v", nrow =6, ncol=1,legend = "top", common.legend = TRUE)

  q3_graphs<- ggarrange(
  deconv_type_plots(q3_results,"Quantiseq", "Q3 Quantiseq"),
  deconv_type_plots(q3_results,"EPIC", "Q3 Epic"),
  deconv_type_plots(q3_results,"MCP", "Q3 MCP"),
  deconv_type_plots(q3_results,"Spotlight", "Q3 Spotlight"),
  deconv_type_plots(q3_results,"Spatial_deconv_cus", "Q3 Spatial Decon ( custom signature 8k)"),
  deconv_type_plots(q3_results,"Spatial_deconv_tme", "Q3 Spatial Decon (TME signature)"),
  widths=c(1,1,1,1,1,1), align="v", nrow =6, ncol=1,common.legend = TRUE,legend = "top")

quantile_graphs<- ggarrange(
  deconv_type_plots(quantile_results,"Quantiseq", "Quantile Quantiseq"),
  deconv_type_plots(quantile_results,"EPIC", "Quantile Epic"),
  deconv_type_plots(quantile_results,"MCP", "Quantile MCP"),
  deconv_type_plots(quantile_results,"Spotlight", "Quantile Spotlight"),
  deconv_type_plots(quantile_results,"Spatial_deconv_cus", "Quantile Spatial Decon ( custom signature 8k)"),
  deconv_type_plots(quantile_results,"Spatial_deconv_tme", "Quantile Spatial Decon (TME signature)"),
  widths=c(1,1,1,1,1,1), align="v", nrow =6, ncol=1,common.legend = TRUE,legend = "top")

quantitative_graphs <- ggarrange(
  raw_graphs,tpm_graphs,q3_graphs, quantile_graphs,
  widths = c(1,1,1,1), align = "h", nrow=1, ncol = 4, common.legend = TRUE, legend = "top"
)

pdf("Results/Bootstrapped_graphs/comparing_normalisation_30082023.pdf", height = 25, width = 15,onefile = TRUE)
quantitative_graphs
dev.off()
```

